/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SVG_ASSETS_FILES           9
#define MMAP_SVG_ASSETS_CHECKSUM        0x4512

enum MMAP_SVG_ASSETS_LISTS {
    MMAP_SVG_ASSETS_GRID_SVG = 0,        /*!< grid.svg */
    MMAP_SVG_ASSETS_GRID_OFF_SVG = 1,        /*!< grid_off.svg */
    MMAP_SVG_ASSETS_MAIL_SVG = 2,        /*!< mail.svg */
    MMAP_SVG_ASSETS_MIC_SVG = 3,        /*!< mic.svg */
    MMAP_SVG_ASSETS_MIC_OFF_SVG = 4,        /*!< mic_off.svg */
    MMAP_SVG_ASSETS_USER_PLUS_SVG = 5,        /*!< user_plus.svg */
    MMAP_SVG_ASSETS_VIDEO_SVG = 6,        /*!< video.svg */
    MMAP_SVG_ASSETS_VOLUME_SVG = 7,        /*!< volume.svg */
    MMAP_SVG_ASSETS_VOLUME_OFF_SVG = 8,        /*!< volume_off.svg */
};
