/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_SVG_ASSETS_FILES           3
#define MMAP_SVG_ASSETS_CHECKSUM        0x9C58

enum MMAP_SVG_ASSETS_LISTS {
    MMAP_SVG_ASSETS_1372943623_SVG = 0,        /*!< 1372943623.svg */
    MMAP_SVG_ASSETS_MIC_SVG = 1,        /*!< mic.svg */
    MMAP_SVG_ASSETS_MIC_OFF_SVG = 2,        /*!< mic_off.svg */
};
