// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: ESPPHONE

#include "../ui.h"

void ui_dial_screen_init(void)
{
    ui_dial = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_dial, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_dialKeyboard = lv_obj_create(ui_dial);
    lv_obj_set_width(ui_dialKeyboard, 600);
    lv_obj_set_height(ui_dialKeyboard, 900);
    lv_obj_set_x(ui_dialKeyboard, 0);
    lv_obj_set_y(ui_dialKeyboard, -50);
    lv_obj_set_align(ui_dialKeyboard, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dialKeyboard, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_dialKeyboard, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialKeyboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialKeyboard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialKeyboard, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialKeyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialKeyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_dialKeyboard, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_dialKeyboard, 53, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum1 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum1, 150);
    lv_obj_set_height(ui_dialkbNum1, 150);
    lv_obj_set_x(ui_dialkbNum1, -175);
    lv_obj_set_y(ui_dialkbNum1, -305);
    lv_obj_set_align(ui_dialkbNum1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn1 = lv_btn_create(ui_dialkbNum1);
    lv_obj_set_width(ui_dialkbBtn1, 140);
    lv_obj_set_height(ui_dialkbBtn1, 140);
    lv_obj_set_align(ui_dialkbBtn1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn1, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel1 = lv_label_create(ui_dialkbNum1);
    lv_obj_set_width(ui_dialkbLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel1, 0);
    lv_obj_set_y(ui_dialkbLabel1, -10);
    lv_obj_set_align(ui_dialkbLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel1, "1");
    lv_obj_set_style_text_font(ui_dialkbLabel1, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum2 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum2, 150);
    lv_obj_set_height(ui_dialkbNum2, 150);
    lv_obj_set_x(ui_dialkbNum2, 8);
    lv_obj_set_y(ui_dialkbNum2, -307);
    lv_obj_set_align(ui_dialkbNum2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn2 = lv_btn_create(ui_dialkbNum2);
    lv_obj_set_width(ui_dialkbBtn2, 140);
    lv_obj_set_height(ui_dialkbBtn2, 140);
    lv_obj_set_align(ui_dialkbBtn2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn2, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel2 = lv_label_create(ui_dialkbNum2);
    lv_obj_set_width(ui_dialkbLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel2, 0);
    lv_obj_set_y(ui_dialkbLabel2, -10);
    lv_obj_set_align(ui_dialkbLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel2, "2");
    lv_obj_set_style_text_font(ui_dialkbLabel2, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel3 = lv_label_create(ui_dialkbNum2);
    lv_obj_set_width(ui_dialkbLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel3, 0);
    lv_obj_set_y(ui_dialkbLabel3, 30);
    lv_obj_set_align(ui_dialkbLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel3, "A B C");
    lv_obj_set_style_text_font(ui_dialkbLabel3, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum3 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum3, 150);
    lv_obj_set_height(ui_dialkbNum3, 150);
    lv_obj_set_x(ui_dialkbNum3, 194);
    lv_obj_set_y(ui_dialkbNum3, -307);
    lv_obj_set_align(ui_dialkbNum3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn3 = lv_btn_create(ui_dialkbNum3);
    lv_obj_set_width(ui_dialkbBtn3, 140);
    lv_obj_set_height(ui_dialkbBtn3, 140);
    lv_obj_set_align(ui_dialkbBtn3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn3, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel5 = lv_label_create(ui_dialkbNum3);
    lv_obj_set_width(ui_dialkbLabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel5, 0);
    lv_obj_set_y(ui_dialkbLabel5, -10);
    lv_obj_set_align(ui_dialkbLabel5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel5, "3");
    lv_obj_set_style_text_font(ui_dialkbLabel5, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel4 = lv_label_create(ui_dialkbNum3);
    lv_obj_set_width(ui_dialkbLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel4, 0);
    lv_obj_set_y(ui_dialkbLabel4, 30);
    lv_obj_set_align(ui_dialkbLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel4, "D E F");
    lv_obj_set_style_text_font(ui_dialkbLabel4, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum4 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum4, 150);
    lv_obj_set_height(ui_dialkbNum4, 150);
    lv_obj_set_x(ui_dialkbNum4, -175);
    lv_obj_set_y(ui_dialkbNum4, -124);
    lv_obj_set_align(ui_dialkbNum4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn4 = lv_btn_create(ui_dialkbNum4);
    lv_obj_set_width(ui_dialkbBtn4, 140);
    lv_obj_set_height(ui_dialkbBtn4, 140);
    lv_obj_set_align(ui_dialkbBtn4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn4, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel7 = lv_label_create(ui_dialkbNum4);
    lv_obj_set_width(ui_dialkbLabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel7, 0);
    lv_obj_set_y(ui_dialkbLabel7, -10);
    lv_obj_set_align(ui_dialkbLabel7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel7, "4");
    lv_obj_set_style_text_font(ui_dialkbLabel7, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel6 = lv_label_create(ui_dialkbNum4);
    lv_obj_set_width(ui_dialkbLabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel6, 0);
    lv_obj_set_y(ui_dialkbLabel6, 30);
    lv_obj_set_align(ui_dialkbLabel6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel6, "G H I");
    lv_obj_set_style_text_font(ui_dialkbLabel6, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum5 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum5, 150);
    lv_obj_set_height(ui_dialkbNum5, 150);
    lv_obj_set_x(ui_dialkbNum5, 8);
    lv_obj_set_y(ui_dialkbNum5, -126);
    lv_obj_set_align(ui_dialkbNum5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn5 = lv_btn_create(ui_dialkbNum5);
    lv_obj_set_width(ui_dialkbBtn5, 140);
    lv_obj_set_height(ui_dialkbBtn5, 140);
    lv_obj_set_align(ui_dialkbBtn5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn5, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn5, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel9 = lv_label_create(ui_dialkbNum5);
    lv_obj_set_width(ui_dialkbLabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel9, 0);
    lv_obj_set_y(ui_dialkbLabel9, -10);
    lv_obj_set_align(ui_dialkbLabel9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel9, "5");
    lv_obj_set_style_text_font(ui_dialkbLabel9, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel10 = lv_label_create(ui_dialkbNum5);
    lv_obj_set_width(ui_dialkbLabel10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel10, 0);
    lv_obj_set_y(ui_dialkbLabel10, 30);
    lv_obj_set_align(ui_dialkbLabel10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel10, "J K L");
    lv_obj_set_style_text_font(ui_dialkbLabel10, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum6 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum6, 150);
    lv_obj_set_height(ui_dialkbNum6, 150);
    lv_obj_set_x(ui_dialkbNum6, 197);
    lv_obj_set_y(ui_dialkbNum6, -121);
    lv_obj_set_align(ui_dialkbNum6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn6 = lv_btn_create(ui_dialkbNum6);
    lv_obj_set_width(ui_dialkbBtn6, 140);
    lv_obj_set_height(ui_dialkbBtn6, 140);
    lv_obj_set_align(ui_dialkbBtn6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn6, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn6, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel11 = lv_label_create(ui_dialkbNum6);
    lv_obj_set_width(ui_dialkbLabel11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel11, 0);
    lv_obj_set_y(ui_dialkbLabel11, -10);
    lv_obj_set_align(ui_dialkbLabel11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel11, "6");
    lv_obj_set_style_text_font(ui_dialkbLabel11, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel12 = lv_label_create(ui_dialkbNum6);
    lv_obj_set_width(ui_dialkbLabel12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel12, 0);
    lv_obj_set_y(ui_dialkbLabel12, 30);
    lv_obj_set_align(ui_dialkbLabel12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel12, "M N O");
    lv_obj_set_style_text_font(ui_dialkbLabel12, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum7 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum7, 150);
    lv_obj_set_height(ui_dialkbNum7, 150);
    lv_obj_set_x(ui_dialkbNum7, -172);
    lv_obj_set_y(ui_dialkbNum7, 50);
    lv_obj_set_align(ui_dialkbNum7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn7 = lv_btn_create(ui_dialkbNum7);
    lv_obj_set_width(ui_dialkbBtn7, 140);
    lv_obj_set_height(ui_dialkbBtn7, 140);
    lv_obj_set_align(ui_dialkbBtn7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn7, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn7, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel13 = lv_label_create(ui_dialkbNum7);
    lv_obj_set_width(ui_dialkbLabel13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel13, 0);
    lv_obj_set_y(ui_dialkbLabel13, -10);
    lv_obj_set_align(ui_dialkbLabel13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel13, "7");
    lv_obj_set_style_text_font(ui_dialkbLabel13, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel14 = lv_label_create(ui_dialkbNum7);
    lv_obj_set_width(ui_dialkbLabel14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel14, 0);
    lv_obj_set_y(ui_dialkbLabel14, 30);
    lv_obj_set_align(ui_dialkbLabel14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel14, "P Q R S");
    lv_obj_set_style_text_font(ui_dialkbLabel14, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum8 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum8, 150);
    lv_obj_set_height(ui_dialkbNum8, 150);
    lv_obj_set_x(ui_dialkbNum8, 5);
    lv_obj_set_y(ui_dialkbNum8, 46);
    lv_obj_set_align(ui_dialkbNum8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum8, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn8 = lv_btn_create(ui_dialkbNum8);
    lv_obj_set_width(ui_dialkbBtn8, 140);
    lv_obj_set_height(ui_dialkbBtn8, 140);
    lv_obj_set_align(ui_dialkbBtn8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn8, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn8, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel15 = lv_label_create(ui_dialkbNum8);
    lv_obj_set_width(ui_dialkbLabel15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel15, 0);
    lv_obj_set_y(ui_dialkbLabel15, -10);
    lv_obj_set_align(ui_dialkbLabel15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel15, "8");
    lv_obj_set_style_text_font(ui_dialkbLabel15, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel16 = lv_label_create(ui_dialkbNum8);
    lv_obj_set_width(ui_dialkbLabel16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel16, 0);
    lv_obj_set_y(ui_dialkbLabel16, 30);
    lv_obj_set_align(ui_dialkbLabel16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel16, "T U V");
    lv_obj_set_style_text_font(ui_dialkbLabel16, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum9 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum9, 150);
    lv_obj_set_height(ui_dialkbNum9, 150);
    lv_obj_set_x(ui_dialkbNum9, 188);
    lv_obj_set_y(ui_dialkbNum9, 54);
    lv_obj_set_align(ui_dialkbNum9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum9, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn9 = lv_btn_create(ui_dialkbNum9);
    lv_obj_set_width(ui_dialkbBtn9, 140);
    lv_obj_set_height(ui_dialkbBtn9, 140);
    lv_obj_set_align(ui_dialkbBtn9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn9, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn9, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel17 = lv_label_create(ui_dialkbNum9);
    lv_obj_set_width(ui_dialkbLabel17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel17, 0);
    lv_obj_set_y(ui_dialkbLabel17, -10);
    lv_obj_set_align(ui_dialkbLabel17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel17, "9");
    lv_obj_set_style_text_font(ui_dialkbLabel17, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel18 = lv_label_create(ui_dialkbNum9);
    lv_obj_set_width(ui_dialkbLabel18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel18, 0);
    lv_obj_set_y(ui_dialkbLabel18, 30);
    lv_obj_set_align(ui_dialkbLabel18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel18, "W X Y Z");
    lv_obj_set_style_text_font(ui_dialkbLabel18, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNumx = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNumx, 150);
    lv_obj_set_height(ui_dialkbNumx, 150);
    lv_obj_set_x(ui_dialkbNumx, -178);
    lv_obj_set_y(ui_dialkbNumx, 230);
    lv_obj_set_align(ui_dialkbNumx, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNumx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNumx, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNumx, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNumx, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNumx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNumx, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtnx = lv_btn_create(ui_dialkbNumx);
    lv_obj_set_width(ui_dialkbBtnx, 140);
    lv_obj_set_height(ui_dialkbBtnx, 140);
    lv_obj_set_align(ui_dialkbBtnx, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtnx, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtnx, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtnx, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtnx, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtnx, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel19 = lv_label_create(ui_dialkbNumx);
    lv_obj_set_width(ui_dialkbLabel19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel19, -1);
    lv_obj_set_y(ui_dialkbLabel19, 20);
    lv_obj_set_align(ui_dialkbLabel19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel19, "*");
    lv_obj_set_style_text_font(ui_dialkbLabel19, &ui_font_OPPOSansRegular70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNum0 = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNum0, 150);
    lv_obj_set_height(ui_dialkbNum0, 150);
    lv_obj_set_x(ui_dialkbNum0, 5);
    lv_obj_set_y(ui_dialkbNum0, 226);
    lv_obj_set_align(ui_dialkbNum0, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNum0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNum0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNum0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNum0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNum0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNum0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtn0 = lv_btn_create(ui_dialkbNum0);
    lv_obj_set_width(ui_dialkbBtn0, 140);
    lv_obj_set_height(ui_dialkbBtn0, 140);
    lv_obj_set_align(ui_dialkbBtn0, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtn0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtn0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtn0, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtn0, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtn0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel21 = lv_label_create(ui_dialkbNum0);
    lv_obj_set_width(ui_dialkbLabel21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel21, 0);
    lv_obj_set_y(ui_dialkbLabel21, -10);
    lv_obj_set_align(ui_dialkbLabel21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel21, "0");
    lv_obj_set_style_text_font(ui_dialkbLabel21, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel22 = lv_label_create(ui_dialkbNum0);
    lv_obj_set_width(ui_dialkbLabel22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dialkbLabel22, 0);
    lv_obj_set_y(ui_dialkbLabel22, 30);
    lv_obj_set_align(ui_dialkbLabel22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel22, "+");
    lv_obj_set_style_text_font(ui_dialkbLabel22, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbNumj = lv_obj_create(ui_dialKeyboard);
    lv_obj_set_width(ui_dialkbNumj, 150);
    lv_obj_set_height(ui_dialkbNumj, 150);
    lv_obj_set_x(ui_dialkbNumj, 196);
    lv_obj_set_y(ui_dialkbNumj, 230);
    lv_obj_set_align(ui_dialkbNumj, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_dialkbNumj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_dialkbNumj, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbNumj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dialkbNumj, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dialkbNumj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dialkbNumj, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbBtnj = lv_btn_create(ui_dialkbNumj);
    lv_obj_set_width(ui_dialkbBtnj, 140);
    lv_obj_set_height(ui_dialkbBtnj, 140);
    lv_obj_set_align(ui_dialkbBtnj, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialkbBtnj, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialkbBtnj, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialkbBtnj, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialkbBtnj, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialkbBtnj, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialkbLabel23 = lv_label_create(ui_dialkbNumj);
    lv_obj_set_width(ui_dialkbLabel23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dialkbLabel23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_dialkbLabel23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dialkbLabel23, "#");
    lv_obj_set_style_text_font(ui_dialkbLabel23, &ui_font_OPPOSansBold50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialBtnAnswer = lv_btn_create(ui_dial);
    lv_obj_set_width(ui_dialBtnAnswer, 140);
    lv_obj_set_height(ui_dialBtnAnswer, 140);
    lv_obj_set_x(ui_dialBtnAnswer, 0);
    lv_obj_set_y(ui_dialBtnAnswer, 486);
    lv_obj_set_align(ui_dialBtnAnswer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialBtnAnswer, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialBtnAnswer, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialBtnAnswer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialBtnAnswer, lv_color_hex(0x4CC55C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialBtnAnswer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_dialBtnAnswer, &ui_img_352369578, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dialBtnBack = lv_btn_create(ui_dial);
    lv_obj_set_width(ui_dialBtnBack, 70);
    lv_obj_set_height(ui_dialBtnBack, 70);
    lv_obj_set_x(ui_dialBtnBack, 203);
    lv_obj_set_y(ui_dialBtnBack, 486);
    lv_obj_set_align(ui_dialBtnBack, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_dialBtnBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_dialBtnBack, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_dialBtnBack, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dialBtnBack, lv_color_hex(0x4CC55C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dialBtnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_dialBtnBack, &ui_img_backspace_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_dialBtnBack, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_dialBtnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_dialBtnBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_dialBtnBack, &ui_img_backspace_png, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_opa(ui_dialBtnBack, 220, LV_PART_MAIN | LV_STATE_PRESSED);

}
