// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ESPPHONE

#include "../ui.h"

void ui_oncall_screen_init(void)
{
    ui_oncall = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_oncall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_oncall, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_oncall, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label55 = lv_label_create(ui_oncall);
    lv_obj_set_width(ui_Label55, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label55, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label55, 0);
    lv_obj_set_y(ui_Label55, -423);
    lv_obj_set_align(ui_Label55, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label55, "espPhone");
    lv_obj_set_style_text_color(ui_Label55, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label55, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label55, &ui_font_OPPOSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label35 = lv_label_create(ui_oncall);
    lv_obj_set_width(ui_Label35, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label35, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label35, 0);
    lv_obj_set_y(ui_Label35, -497);
    lv_obj_set_align(ui_Label35, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label35, "ESP_Friends");
    lv_obj_set_style_text_color(ui_Label35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label35, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label35, &ui_font_OPPOSansRegular70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Roller1 = lv_roller_create(ui_oncall);
    lv_roller_set_options(ui_Roller1,
                          "Sorry, I can't come to the phone right now.\nI'll be right there\nI'll call you later.", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_Roller1, 720);
    lv_obj_set_height(ui_Roller1, 273);
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, 500);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Roller1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &ui_font_OPPOSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x141414), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Roller1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Roller1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Roller1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_Roller1, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Roller1, &ui_font_OPPOSansRegular34, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Panel37 = lv_obj_create(ui_oncall);
    lv_obj_set_width(ui_Panel37, 566);
    lv_obj_set_height(ui_Panel37, 435);
    lv_obj_set_x(ui_Panel37, 0);
    lv_obj_set_y(ui_Panel37, 335);
    lv_obj_set_align(ui_Panel37, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel37, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel37, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Panel37, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel37, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel37, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Panel37, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Panel37, 208, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel38 = lv_obj_create(ui_Panel37);
    lv_obj_set_width(ui_Panel38, 150);
    lv_obj_set_height(ui_Panel38, 147);
    lv_obj_set_x(ui_Panel38, -178);
    lv_obj_set_y(ui_Panel38, -105);
    lv_obj_set_align(ui_Panel38, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel38, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel38, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel38, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_Panel38);
    lv_image_set_src(ui_Image7, &ui_img_126583460);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label56 = lv_label_create(ui_Panel38);
    lv_obj_set_width(ui_Label56, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label56, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label56, 0);
    lv_obj_set_y(ui_Label56, 55);
    lv_obj_set_align(ui_Label56, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label56, "Remind Me");
    lv_obj_set_style_text_color(ui_Label56, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label56, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label56, &ui_font_OPPOSansBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel35 = lv_obj_create(ui_Panel37);
    lv_obj_set_width(ui_Panel35, 150);
    lv_obj_set_height(ui_Panel35, 147);
    lv_obj_set_x(ui_Panel35, 156);
    lv_obj_set_y(ui_Panel35, -119);
    lv_obj_set_align(ui_Panel35, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel35, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel35, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Panel35);
    lv_image_set_src(ui_Image1, &ui_img_2054516389);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label53 = lv_label_create(ui_Panel35);
    lv_obj_set_width(ui_Label53, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label53, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label53, 0);
    lv_obj_set_y(ui_Label53, 55);
    lv_obj_set_align(ui_Label53, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label53, "Message");
    lv_obj_set_style_text_color(ui_Label53, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label53, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label53, &ui_font_OPPOSansBold25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Panel37);
    lv_obj_set_width(ui_Panel3, 157);
    lv_obj_set_height(ui_Panel3, 246);
    lv_obj_set_x(ui_Panel3, 165);
    lv_obj_set_y(ui_Panel3, 115);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_button_create(ui_Panel3);
    lv_obj_set_width(ui_Button21, 140);
    lv_obj_set_height(ui_Button21, 140);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button21, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button21, lv_color_hex(0x4CC55C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button21, &ui_img_352369578, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, 100);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "Answer");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &ui_font_OPPOSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel22 = lv_obj_create(ui_Panel37);
    lv_obj_set_width(ui_Panel22, 157);
    lv_obj_set_height(ui_Panel22, 246);
    lv_obj_set_x(ui_Panel22, -170);
    lv_obj_set_y(ui_Panel22, 106);
    lv_obj_set_align(ui_Panel22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel22, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button20 = lv_button_create(ui_Panel22);
    lv_obj_set_width(ui_Button20, 140);
    lv_obj_set_height(ui_Button20, 140);
    lv_obj_set_align(ui_Button20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button20, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button20, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button20, lv_color_hex(0xF44937), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button20, &ui_img_352369578, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_Panel22);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 0);
    lv_obj_set_y(ui_Label31, 100);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Decline");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &ui_font_OPPOSansRegular34, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image1, ui_event_Image1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_oncall, ui_event_oncall, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button21, ui_event_button_answer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button20, ui_event_button_decline, LV_EVENT_ALL, NULL);

}
