// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ESPPHONE

#include "../ui.h"

void ui_statedark_screen_init(void)
{
    ui_statedark = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_statedark, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statedark, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statedark, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statesBar1 = lv_obj_create(ui_statedark);
    lv_obj_set_width(ui_statesBar1, 720);
    lv_obj_set_height(ui_statesBar1, 20);
    lv_obj_set_align(ui_statesBar1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statesBar1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statesBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statesBar1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statesBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statesBar1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1 = lv_label_create(ui_statesBar1);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1, -331);
    lv_obj_set_y(ui_time1, 1);
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "12:39");
    lv_obj_set_style_text_color(ui_time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_statesBar1);
    lv_image_set_src(ui_Image3, &ui_img_1328003813);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image3, 321);
    lv_obj_set_y(ui_Image3, 0);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image3, 220);

    ui_Image4 = lv_image_create(ui_statesBar1);
    lv_image_set_src(ui_Image4, &ui_img_667377057);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image4, 274);
    lv_obj_set_y(ui_Image4, -1);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image4, 200);

    ui_Image6 = lv_image_create(ui_statesBar1);
    lv_image_set_src(ui_Image6, &ui_img_336861511);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image6, 226);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image6, 130);

}
