// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ESPPHONE

#include "../ui.h"

void ui_statelight_screen_init(void)
{
    ui_statelight = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_statelight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_statelight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statelight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_statesBar = lv_obj_create(ui_statelight);
    lv_obj_set_width(ui_statesBar, 720);
    lv_obj_set_height(ui_statesBar, 20);
    lv_obj_set_align(ui_statesBar, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_statesBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_statesBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_statesBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_statesBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_statesBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_statesBar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -331);
    lv_obj_set_y(ui_time, 1);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "12:39");
    lv_obj_set_style_text_font(ui_time, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_statesBar);
    lv_image_set_src(ui_Image15, &ui_img_1152878764);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image15, 321);
    lv_obj_set_y(ui_Image15, 0);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image15, 220);

    ui_Image2 = lv_image_create(ui_statesBar);
    lv_image_set_src(ui_Image2, &ui_img_1515518950);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image2, 274);
    lv_obj_set_y(ui_Image2, -1);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image2, 200);

    ui_Image5 = lv_image_create(ui_statesBar);
    lv_image_set_src(ui_Image5, &ui_img_1755492943);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Image5, 226);
    lv_obj_set_y(ui_Image5, 0);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
