// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: ESPPHONE

#include "../ui.h"

void ui_stateLight_screen_init(void)
{
    ui_stateLight = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_stateLight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_stateLight, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_stateLight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightBar = lv_obj_create(ui_stateLight);
    lv_obj_set_width(ui_LightBar, 720);
    lv_obj_set_height(ui_LightBar, 20);
    lv_obj_set_align(ui_LightBar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_LightBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LightBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LightBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightTime = lv_label_create(ui_LightBar);
    lv_obj_set_width(ui_lightTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lightTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lightTime, -331);
    lv_obj_set_y(ui_lightTime, 1);
    lv_obj_set_align(ui_lightTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lightTime, "12:39");
    lv_obj_set_style_text_font(ui_lightTime, &ui_font_OPPOSansBold14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lightBattery = lv_img_create(ui_LightBar);
    lv_img_set_src(ui_lightBattery, &ui_img_1152878764);
    lv_obj_set_width(ui_lightBattery, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_lightBattery, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_lightBattery, 321);
    lv_obj_set_y(ui_lightBattery, 0);
    lv_obj_set_align(ui_lightBattery, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightBattery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_lightBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightBattery, 220);

    ui_lightWifi = lv_img_create(ui_LightBar);
    lv_img_set_src(ui_lightWifi, &ui_img_1515518950);
    lv_obj_set_width(ui_lightWifi, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_lightWifi, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_lightWifi, 274);
    lv_obj_set_y(ui_lightWifi, -1);
    lv_obj_set_align(ui_lightWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_lightWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_lightWifi, 200);

    ui_lightMobile = lv_img_create(ui_LightBar);
    lv_img_set_src(ui_lightMobile, &ui_img_1755492943);
    lv_obj_set_width(ui_lightMobile, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_lightMobile, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_lightMobile, 226);
    lv_obj_set_y(ui_lightMobile, 0);
    lv_obj_set_align(ui_lightMobile, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lightMobile, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(ui_lightMobile, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
