// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: ESPPHONE

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void turnOFF_Animation(lv_obj_t * TargetObject, int delay);
void turnON_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_stateLight
void ui_stateLight_screen_init(void);
lv_obj_t * ui_stateLight;
lv_obj_t * ui_LightBar;
lv_obj_t * ui_lightTime;
lv_obj_t * ui_lightBattery;
lv_obj_t * ui_lightWifi;
lv_obj_t * ui_lightMobile;


// SCREEN: ui_dial
void ui_dial_screen_init(void);
lv_obj_t * ui_dial;
lv_obj_t * ui_dialKeyboard;
lv_obj_t * ui_dialkbNum1;
lv_obj_t * ui_dialkbBtn1;
lv_obj_t * ui_dialkbLabel1;
lv_obj_t * ui_dialkbNum2;
lv_obj_t * ui_dialkbBtn2;
lv_obj_t * ui_dialkbLabel2;
lv_obj_t * ui_dialkbLabel3;
lv_obj_t * ui_dialkbNum3;
lv_obj_t * ui_dialkbBtn3;
lv_obj_t * ui_dialkbLabel5;
lv_obj_t * ui_dialkbLabel4;
lv_obj_t * ui_dialkbNum4;
lv_obj_t * ui_dialkbBtn4;
lv_obj_t * ui_dialkbLabel7;
lv_obj_t * ui_dialkbLabel6;
lv_obj_t * ui_dialkbNum5;
lv_obj_t * ui_dialkbBtn5;
lv_obj_t * ui_dialkbLabel9;
lv_obj_t * ui_dialkbLabel10;
lv_obj_t * ui_dialkbNum6;
lv_obj_t * ui_dialkbBtn6;
lv_obj_t * ui_dialkbLabel11;
lv_obj_t * ui_dialkbLabel12;
lv_obj_t * ui_dialkbNum7;
lv_obj_t * ui_dialkbBtn7;
lv_obj_t * ui_dialkbLabel13;
lv_obj_t * ui_dialkbLabel14;
lv_obj_t * ui_dialkbNum8;
lv_obj_t * ui_dialkbBtn8;
lv_obj_t * ui_dialkbLabel15;
lv_obj_t * ui_dialkbLabel16;
lv_obj_t * ui_dialkbNum9;
lv_obj_t * ui_dialkbBtn9;
lv_obj_t * ui_dialkbLabel17;
lv_obj_t * ui_dialkbLabel18;
lv_obj_t * ui_dialkbNumx;
lv_obj_t * ui_dialkbBtnx;
lv_obj_t * ui_dialkbLabel19;
lv_obj_t * ui_dialkbNum0;
lv_obj_t * ui_dialkbBtn0;
lv_obj_t * ui_dialkbLabel21;
lv_obj_t * ui_dialkbLabel22;
lv_obj_t * ui_dialkbNumj;
lv_obj_t * ui_dialkbBtnj;
lv_obj_t * ui_dialkbLabel23;
lv_obj_t * ui_dialBtnAnswer;
lv_obj_t * ui_dialBtnBack;


// SCREEN: ui_answer
void ui_answer_screen_init(void);
void ui_event_answer(lv_event_t * e);
lv_obj_t * ui_answer;
lv_obj_t * ui_ansFuc;
lv_obj_t * ui_ansFucmute;
void ui_event_ansBtnmute(lv_event_t * e);
lv_obj_t * ui_ansBtnmute;
lv_obj_t * ui_ansFucLabel1;
lv_obj_t * ui_ansFucSlash;
lv_obj_t * ui_slash;
lv_obj_t * ui_ansFuckeypad;
void ui_event_ansBtnkeypad(lv_event_t * e);
lv_obj_t * ui_ansBtnkeypad;
lv_obj_t * ui_ansFucLabel2;
lv_obj_t * ui_ansFucaudio;
lv_obj_t * ui_ansBtnaudio;
lv_obj_t * ui_ansFucLabel3;
lv_obj_t * ui_ansFuccall;
lv_obj_t * ui_ansBtncall;
lv_obj_t * ui_ansFucLabel4;
lv_obj_t * ui_ansFucfacetime;
lv_obj_t * ui_ansBtnfacetime;
lv_obj_t * ui_ansFucLabel5;
lv_obj_t * ui_ansFuccontact;
lv_obj_t * ui_ansBtncontact;
lv_obj_t * ui_ansFucLabel6;
lv_obj_t * ui_ansLabelName;
lv_obj_t * ui_ansLabelTime;
lv_obj_t * ui_ansBtnDEC;
lv_obj_t * ui_answerKeyboard;
lv_obj_t * ui_ansKbNum1;
lv_obj_t * ui_ansKbBtn1;
lv_obj_t * ui_ansKbLabel1;
lv_obj_t * ui_ansKbNum2;
lv_obj_t * ui_ansKbBtn2;
lv_obj_t * ui_ansKbLabel2;
lv_obj_t * ui_ansKbLabel32;
lv_obj_t * ui_ansKbNum3;
lv_obj_t * ui_ansKbBtn3;
lv_obj_t * ui_ansKbLabel3;
lv_obj_t * ui_ansKbLabel34;
lv_obj_t * ui_ansKbNum4;
lv_obj_t * ui_ansKbBtn4;
lv_obj_t * ui_ansKbLabel4;
lv_obj_t * ui_ansKbLabel37;
lv_obj_t * ui_ansKbNum5;
lv_obj_t * ui_ansKbBtn5;
lv_obj_t * ui_ansKbLabel5;
lv_obj_t * ui_ansKbLabel39;
lv_obj_t * ui_ansKbNum6;
lv_obj_t * ui_ansKbBtn6;
lv_obj_t * ui_ansKbLabel6;
lv_obj_t * ui_ansKbLabel41;
lv_obj_t * ui_ansKbNum7;
lv_obj_t * ui_ansKbBtn7;
lv_obj_t * ui_ansKbLabel7;
lv_obj_t * ui_ansKbLabel44;
lv_obj_t * ui_ansKbNum8;
lv_obj_t * ui_ansKbBtn8;
lv_obj_t * ui_ansKbLabel8;
lv_obj_t * ui_ansKbLabel46;
lv_obj_t * ui_ansKbNum9;
lv_obj_t * ui_ansKbBtn9;
lv_obj_t * ui_ansKbLabel9;
lv_obj_t * ui_ansKbLabel48;
lv_obj_t * ui_ansKbNumx;
lv_obj_t * ui_ansKbBtnx;
lv_obj_t * ui_ansKbLabelx;
lv_obj_t * ui_ansKbNum0;
lv_obj_t * ui_ansKbBtn0;
lv_obj_t * ui_ansKbLabel0;
lv_obj_t * ui_ansKbLabel51;
lv_obj_t * ui_ansKbNumj;
lv_obj_t * ui_ansKbBtnj;
lv_obj_t * ui_ansKbLabelj;


// SCREEN: ui_stateDark
void ui_stateDark_screen_init(void);
lv_obj_t * ui_stateDark;
lv_obj_t * ui_darkBar;
lv_obj_t * ui_darkTime;
lv_obj_t * ui_darkBattery;
lv_obj_t * ui_darkWifi;
lv_obj_t * ui_darkMobile;


// SCREEN: ui_oncall
void ui_oncall_screen_init(void);
void ui_event_oncall(lv_event_t * e);
lv_obj_t * ui_oncall;
lv_obj_t * ui_oncallLabelPhone;
lv_obj_t * ui_oncallLabelName;
lv_obj_t * ui_oncallMsg;
lv_obj_t * ui_oncallFuc;
lv_obj_t * ui_oncallFucRemind;
lv_obj_t * ui_Image7;
lv_obj_t * ui_oncallFucLabel1;
lv_obj_t * ui_oncallFucMsg;
void ui_event_Image1(lv_event_t * e);
lv_obj_t * ui_Image1;
lv_obj_t * ui_oncallFucLabel2;
lv_obj_t * ui_oncallBFucAns;
lv_obj_t * ui_oncallBtnAns;
lv_obj_t * ui_Label27;
lv_obj_t * ui_oncallBFucDec;
lv_obj_t * ui_oncallBtnDec;
lv_obj_t * ui_Label31;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_1496073666[1] = {&ui_img_126583460};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void turnOFF_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, -100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}
void turnON_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 500);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x);
    lv_anim_set_values(&PropertyAnimation_0, 0, 100);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_ease_out);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_dial(lv_event_t *e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        lv_obj_set_parent(ui_dial, ui_stateLight);
    }
}
void ui_event_answer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        lv_obj_set_parent(ui_answer, ui_stateDark);
    }
    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_answerKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_ansFuc, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_ansBtnkeypad, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_ansBtnmute(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        turnON_Animation(ui_slash, 0);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        turnOFF_Animation(ui_slash, 0);
    }
}
void ui_event_ansBtnkeypad(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_answerKeyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_ansFuc, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_oncall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START)
    {
        lv_obj_set_parent(ui_oncall, ui_stateDark);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_oncallFuc, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_oncallMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_Image1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_oncallFuc, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_oncallMsg, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_rotation(dispp, LV_DISP_ROT_270);
    lv_disp_set_theme(dispp, theme);
    ui_stateLight_screen_init();
    ui_dial_screen_init();
    ui_answer_screen_init();
    ui_stateDark_screen_init();
    ui_oncall_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_answer);
}
