// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: ESPPHONE

#ifndef _ESPPHONE_UI_H
#define _ESPPHONE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void turnOFF_Animation(lv_obj_t * TargetObject, int delay);
void turnON_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_statelight
void ui_statelight_screen_init(void);
extern lv_obj_t * ui_statelight;
extern lv_obj_t * ui_statesBar;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image5;
// SCREEN: ui_dial
void ui_dial_screen_init(void);
void ui_event_dial(lv_event_t * e);
extern lv_obj_t * ui_dial;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Button10;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Button11;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Button12;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Button13;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Button36;
// SCREEN: ui_answer
void ui_answer_screen_init(void);
void ui_event_answer(lv_event_t * e);
void ui_event_hangup(lv_event_t * e);
extern lv_obj_t * ui_answer;
extern lv_obj_t * ui_Panel29;
extern lv_obj_t * ui_Panel15;
void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_panel21;
extern lv_obj_t * ui_slash;
extern lv_obj_t * ui_Panel16;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Panel17;
extern lv_obj_t * ui_Button15;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel18;
extern lv_obj_t * ui_Button16;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Panel19;
extern lv_obj_t * ui_Button17;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Panel20;
extern lv_obj_t * ui_Button18;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Button26;
extern lv_obj_t * ui_Panel36;
extern lv_obj_t * ui_Panel21;
extern lv_obj_t * ui_Button35;
extern lv_obj_t * ui_Label54;
extern lv_obj_t * ui_Panel23;
extern lv_obj_t * ui_Button34;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Panel24;
extern lv_obj_t * ui_Button22;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_Panel25;
extern lv_obj_t * ui_Button23;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Panel26;
extern lv_obj_t * ui_Button24;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Panel27;
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Label40;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Panel28;
extern lv_obj_t * ui_Button28;
extern lv_obj_t * ui_Label42;
extern lv_obj_t * ui_Label44;
extern lv_obj_t * ui_Panel30;
extern lv_obj_t * ui_Button29;
extern lv_obj_t * ui_Label45;
extern lv_obj_t * ui_Label46;
extern lv_obj_t * ui_Panel31;
extern lv_obj_t * ui_Button30;
extern lv_obj_t * ui_Label47;
extern lv_obj_t * ui_Label48;
extern lv_obj_t * ui_Panel32;
extern lv_obj_t * ui_Button31;
extern lv_obj_t * ui_Label49;
extern lv_obj_t * ui_Panel33;
extern lv_obj_t * ui_Button32;
extern lv_obj_t * ui_Label50;
extern lv_obj_t * ui_Label51;
extern lv_obj_t * ui_Panel34;
extern lv_obj_t * ui_Button33;
extern lv_obj_t * ui_Label52;
// SCREEN: ui_statedark
void ui_statedark_screen_init(void);
extern lv_obj_t * ui_statedark;
extern lv_obj_t * ui_statesBar1;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Image6;
// SCREEN: ui_oncall
void ui_oncall_screen_init(void);
void ui_event_oncall(lv_event_t * e);
void ui_event_button_answer(lv_event_t * e);
void ui_event_button_decline(lv_event_t * e);
extern lv_obj_t * ui_oncall;
extern lv_obj_t * ui_Label55;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_Panel37;
extern lv_obj_t * ui_Panel38;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label56;
extern lv_obj_t * ui_Panel35;
void ui_event_Image1(lv_event_t * e);
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label53;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Button21;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Panel22;
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_1152878764);    // assets/电池电量.png
LV_IMG_DECLARE(ui_img_1515518950);    // assets/wifi (1).png
LV_IMG_DECLARE(ui_img_1755492943);    // assets/信号.png
LV_IMG_DECLARE(ui_img_352369578);    // assets/拨号 (1).png
LV_IMG_DECLARE(ui_img_backspace_png);    // assets/backspace.png
LV_IMG_DECLARE(ui_img_988448286);    // assets/麦克风.png
LV_IMG_DECLARE(ui_img_753335661);    // assets/麦克风-dark.png
LV_IMG_DECLARE(ui_img_keypad_png);    // assets/keypad.png
LV_IMG_DECLARE(ui_img_1143594758);    // assets/keypad-dark.png
LV_IMG_DECLARE(ui_img_1817873855);    // assets/audio-off.png
LV_IMG_DECLARE(ui_img_495558844);    // assets/audio-high.png
LV_IMG_DECLARE(ui_img_addcontacts_png);    // assets/AddContacts.png
LV_IMG_DECLARE(ui_img_facetime_fill_png);    // assets/facetime_fill.png
LV_IMG_DECLARE(ui_img_contacts_png);    // assets/contacts.png
LV_IMG_DECLARE(ui_img_1328003813);    // assets/电池电量-dark.png
LV_IMG_DECLARE(ui_img_667377057);    // assets/wifi-dark.png
LV_IMG_DECLARE(ui_img_336861511);    // assets/信号强度1-dark.png
LV_IMG_DECLARE(ui_img_126583460);    // assets/闹钟3.png
LV_IMG_DECLARE(ui_img_2054516389);    // assets/信息 (1).png



LV_FONT_DECLARE(ui_font_DISPLAYTFB25);
LV_FONT_DECLARE(ui_font_OPPOSansBold14);
LV_FONT_DECLARE(ui_font_OPPOSansBold25);
LV_FONT_DECLARE(ui_font_OPPOSansBold50);
LV_FONT_DECLARE(ui_font_OPPOSansRegular14);
LV_FONT_DECLARE(ui_font_OPPOSansRegular20);
LV_FONT_DECLARE(ui_font_OPPOSansRegular34);
LV_FONT_DECLARE(ui_font_OPPOSansRegular70);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
